global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "steam_app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "steammicro:25502"
          - "simple-notification-service:25501"
